/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteSkillsRouteImport } from './routes/_site/skills'
import { Route as SiteResumeRouteImport } from './routes/_site/resume'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteProjectsIndexRouteImport } from './routes/_site/projects/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as SiteProjectsSlugRouteImport } from './routes/_site/projects/$slug'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin.login'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSkillsRoute = SiteSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResumeRoute = SiteResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsIndexRoute = SiteProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteProjectsSlugRoute = SiteProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/resume': typeof SiteResumeRoute
  '/skills': typeof SiteSkillsRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/projects/': typeof SiteProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/resume': typeof SiteResumeRoute
  '/skills': typeof SiteSkillsRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/projects': typeof SiteProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/resume': typeof SiteResumeRoute
  '/_site/skills': typeof SiteSkillsRoute
  '/_site/': typeof SiteIndexRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_site/projects/$slug': typeof SiteProjectsSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_site/projects/': typeof SiteProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/skills'
    | '/admin/login'
    | '/projects/$slug'
    | '/admin/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/skills'
    | '/admin/login'
    | '/projects/$slug'
    | '/admin'
    | '/projects'
  id:
    | '__root__'
    | '/_admin'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/resume'
    | '/_site/skills'
    | '/_site/'
    | '/_admin/admin/login'
    | '/_site/projects/$slug'
    | '/_admin/admin/'
    | '/_site/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/skills': {
      id: '/_site/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SiteSkillsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/resume': {
      id: '/_site/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof SiteResumeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/': {
      id: '/_site/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof SiteProjectsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/projects/$slug': {
      id: '/_site/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof SiteProjectsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteResumeRoute: typeof SiteResumeRoute
  SiteSkillsRoute: typeof SiteSkillsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProjectsSlugRoute: typeof SiteProjectsSlugRoute
  SiteProjectsIndexRoute: typeof SiteProjectsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteResumeRoute: SiteResumeRoute,
  SiteSkillsRoute: SiteSkillsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProjectsSlugRoute: SiteProjectsSlugRoute,
  SiteProjectsIndexRoute: SiteProjectsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
